In [2]:
import pandas as pd

# QC of sensor data

There is NIVA sensor data for 2023 for Glomma. Aim in this notebook is to do a quick manual QC of this data. There are already automated QC procedures in place, but these tend to be too stringent for some parameters, e.g. turbidity which is spiky. Aim in AquaInfra to work with Ivana to improve these QC routines.

Data is from NIVA station 'Baterød', which I think is located adjacent to where the elveovervåking samples are taking (needs checking!). Leah JB downloaded the latest data on 2024-08-28 and it is stored here: aquainfra/data/river/sensors/glomma_sensor_data_raw_2024-08-28.csv

To do:
* Plot the 6 data columns and see whether there are dodgy values
* Work with Ivana to see whether the quality flags that have already been assigned are useful in identifying dodgy values or are too lax/strict
* Come up with new quality flags to remove dodgy data
* Fill any gaps in the data in a sensible way. E.g. linear interpolation if they are short
* Save cleaned high frequency data
* Convert to daily means and save again

In [5]:
fpath = r'../../data/river/sensors/glomma_sensor_data_raw_2024-08-28.csv'
df = pd.read_csv(fpath, index_col=0, parse_dates=True)
df.head()

,Date,Time,CDOMdigitalFinal (µg/L),QC flag CDOMdigitalFinal,PhValue_Avg (-),QC flag PhValue_Avg,Temp_water_Avg (degC),QC flag Temp_water_Avg,CondValue_Avg (µS/cm),QC flag CondValue_Avg,Turbidity_Avg (NTU),QC flag Turbidity_Avg,Salinity_Avg (-),QC flag Salinity_Avg
Timestamp,,,,,,,,,,,,,,
2023-02-02 15:00:00,2023-02-02,15:00:00,76.04,NaN,6.464,NaN,0.103,NaN,35.52,NaN,9.060,NaN,0.019,NaN
2023-02-02 16:00:00,2023-02-02,16:00:00,76.01,NaN,6.370,NaN,0.121,NaN,35.56,NaN,8.070,NaN,0.019,NaN
2023-02-02 17:00:00,2023-02-02,17:00:00,75.91,NaN,6.373,NaN,0.130,NaN,35.47,NaN,8.570,NaN,0.019,NaN
2023-02-02 18:00:00,2023-02-02,18:00:00,75.84,NaN,6.427,NaN,0.121,NaN,35.35,NaN,8.580,NaN,0.019,NaN
2023-02-02 19:00:00,2023-02-02,19:00:00,75.83,Good,6.523,Good,0.090,Good,35.30,Good,7.268,Good,0.019,NaN